// Auto-generated embedded HTML
static const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no\">\n"
"<title>RID 无人机管理系统</title>\n"
"<style>\n"
":root{--bg:#0a0e17;--card:#141b27;--accent:#00d4ff;--accent2:#7c3aed;--text:#e2e8f0;--text2:#94a3b8;--danger:#ef4444;--success:#22c55e;--warn:#f59e0b;--border:#1e293b}\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"
"body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;background:var(--bg);color:var(--text);min-height:100vh}\n"
"header{background:linear-gradient(135deg,var(--accent2),#2563eb);padding:20px 16px;text-align:center;position:sticky;top:0;z-index:100}\n"
"header h1{font-size:1.4em;font-weight:700}header .sub{font-size:.85em;opacity:.85;margin-top:4px}\n"
"nav{display:flex;background:var(--card);border-bottom:1px solid var(--border);position:sticky;top:72px;z-index:99}\n"
"nav a{flex:1;min-width:80px;text-align:center;padding:12px 8px;color:var(--text2);text-decoration:none;font-size:.85em;font-weight:500;border-bottom:2px solid transparent}\n"
"nav a.active{color:var(--accent);border-bottom-color:var(--accent)}\n"
".page{display:none;padding:16px;animation:fadeIn .3s}.page.active{display:block}\n"
"@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}\n"
".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin-bottom:20px}\n"
".stat-card{background:var(--card);border-radius:16px;padding:18px 16px;text-align:center;border:1px solid var(--border)}\n"
".stat-card .num{font-size:2em;font-weight:800;background:linear-gradient(135deg,var(--accent),var(--accent2));-webkit-background-clip:text;-webkit-text-fill-color:transparent}\n"
".stat-card .label{font-size:.8em;color:var(--text2);margin-top:4px;text-transform:uppercase;letter-spacing:1px}\n"
".card{background:var(--card);border-radius:16px;padding:16px;margin-bottom:12px;border:1px solid var(--border)}\n"
".card h3{font-size:1em;margin-bottom:12px;color:var(--accent)}\n"
".drone-list .drone-item{display:flex;align-items:center;padding:14px 12px;background:var(--bg);border-radius:12px;margin-bottom:8px;cursor:pointer;border:1px solid transparent}\n"
".drone-list .drone-item:hover{border-color:var(--accent);transform:translateX(4px)}\n"
".drone-item .icon{width:44px;height:44px;border-radius:12px;background:linear-gradient(135deg,var(--accent2),#2563eb);display:flex;align-items:center;justify-content:center;font-size:1.4em;margin-right:12px;flex-shrink:0}\n"
".drone-item .info{flex:1;min-width:0}.drone-item .info .name{font-weight:600;font-size:.95em}.drone-item .info .meta{font-size:.78em;color:var(--text2);margin-top:2px}\n"
".drone-item .arrow{color:var(--text2);font-size:1.2em}\n"
".status-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}\n"
".status-dot.online{background:var(--success)}.status-dot.offline{background:var(--text2)}\n"
".detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}\n"
".detail-grid .kv{background:var(--bg);padding:10px 12px;border-radius:8px}\n"
".detail-grid .kv .k{font-size:.75em;color:var(--text2);text-transform:uppercase}.detail-grid .kv .v{font-size:.95em;font-weight:500;margin-top:2px}\n"
".btn{display:inline-flex;align-items:center;justify-content:center;padding:10px 20px;border-radius:10px;font-size:.9em;font-weight:600;cursor:pointer;border:none;transition:all .2s;text-decoration:none;gap:6px}\n"
".btn-primary{background:linear-gradient(135deg,var(--accent2),#2563eb);color:#fff}.btn-primary:hover{transform:translateY(-1px)}\n"
".btn-danger{background:var(--danger);color:#fff}.btn-success{background:var(--success);color:#fff}\n"
".btn-outline{background:transparent;border:1px solid var(--border);color:var(--text)}.btn-block{display:flex;width:100%}\n"
".btn-sm{padding:6px 14px;font-size:.8em;border-radius:8px}\n"
".form-group{margin-bottom:16px}.form-group label{display:block;font-size:.8em;color:var(--text2);margin-bottom:6px;text-transform:uppercase}\n"
".form-group input,.form-group select{width:100%;padding:10px 12px;background:var(--bg);border:1px solid var(--border);border-radius:10px;color:var(--text);font-size:.9em}\n"
".form-group input:focus,.form-group select:focus{outline:none;border-color:var(--accent)}\n"
".form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}\n"
".toggle{position:relative;width:52px;height:28px;flex-shrink:0}.toggle input{display:none}\n"
".toggle .slider{position:absolute;inset:0;background:var(--border);border-radius:28px;cursor:pointer;transition:.3s}\n"
".toggle .slider:before{content:\"\";position:absolute;height:22px;width:22px;left:3px;bottom:3px;background:#fff;border-radius:50%;transition:.3s}\n"
".toggle input:checked+.slider{background:var(--success)}.toggle input:checked+.slider:before{transform:translateX(24px)}\n"
".empty-state{text-align:center;padding:40px 20px;color:var(--text2)}.empty-state .icon{font-size:3em;margin-bottom:12px}\n"
".badge{display:inline-block;padding:3px 8px;border-radius:6px;font-size:.7em;font-weight:600}\n"
".badge-online{background:rgba(34,197,94,.15);color:var(--success)}.badge-offline{background:rgba(148,163,184,.15);color:var(--text2)}\n"
".flex-between{display:flex;justify-content:space-between;align-items:center}\n"
".mt-sm{margin-top:12px}.mb-sm{margin-bottom:12px}.footer{text-align:center;padding:24px;color:var(--text2);font-size:.75em}\n"
".range-wrap{display:flex;align-items:center;gap:12px}\n"
".range-wrap input[type=range]{flex:1}\n"
".range-wrap .range-val{font-size:1.2em;font-weight:700;color:var(--accent);min-width:30px;text-align:center}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header><h1>🛸 RID 无人机管理系统</h1><div class=\"sub\">ESP32-C3 Remote ID Scanner</div></header>\n"
"<nav>\n"
"<a href=\"#dashboard\" class=\"active\" onclick=\"switchTab('dashboard')\">📊 仪表盘</a>\n"
"<a href=\"#drones\" onclick=\"switchTab('drones')\">🚁 无人机</a>\n"
"<a href=\"#simulator\" onclick=\"switchTab('simulator')\">📡 模拟器</a>\n"
"<a href=\"#about\" onclick=\"switchTab('about')\">ℹ️ 关于</a>\n"
"</nav>\n"
"\n"
"<div id=\"dashboard\" class=\"page active\">\n"
"<div class=\"stats\">\n"
"<div class=\"stat-card\"><div class=\"num\" id=\"stat-online\">0</div><div class=\"label\">在线无人机</div></div>\n"
"<div class=\"stat-card\"><div class=\"num\" id=\"stat-heap\">0</div><div class=\"label\">可用内存 KB</div></div>\n"
"<div class=\"stat-card\"><div class=\"num\" id=\"stat-sim\">OFF</div><div class=\"label\">模拟器状态</div></div>\n"
"</div>\n"
"<div class=\"card\"><h3>📋 最近无人机</h3><div class=\"drone-list\" id=\"recent-drones\"></div></div>\n"
"</div>\n"
"\n"
"<div id=\"drones\" class=\"page\">\n"
"<div class=\"flex-between mb-sm\"><h3 style=\"color:var(--accent)\">🚁 无人机列表</h3><span id=\"drone-count\"></span></div>\n"
"<div class=\"card\"><div class=\"drone-list\" id=\"all-drones\"></div><div class=\"empty-state\" id=\"drones-empty\"><div class=\"icon\">📭</div><p>暂无无人机数据</p></div></div>\n"
"</div>\n"
"\n"
"<div id=\"drone-detail\" class=\"page\">\n"
"<div class=\"flex-between mb-sm\"><a href=\"#\" onclick=\"switchTab('drones')\" style=\"color:var(--accent);text-decoration:none;font-size:.9em\">← 返回列表</a></div>\n"
"<div class=\"card\" id=\"detail-content\"></div>\n"
"<div class=\"card\"><h3>🗺️ 导航</h3>\n"
"<a id=\"nav-drone\" class=\"btn btn-primary btn-block\" href=\"#\" target=\"_blank\">📍 一键导航到无人机位置 (高德地图)</a>\n"
"<p id=\"map-hint\" style=\"font-size:.8em;color:var(--text2);margin-top:8px\"></p>\n"
"<a id=\"nav-operator\" class=\"btn btn-outline btn-block mt-sm\" href=\"#\" target=\"_blank\">🧑‍✈️ 导航到飞手位置 (高德地图)</a>\n"
"</div></div>\n"
"\n"
"<div id=\"simulator\" class=\"page\">\n"
"<div class=\"card\"><div class=\"flex-between\"><h3>📡 模拟无人机发送</h3>\n"
"<label class=\"toggle\"><input type=\"checkbox\" id=\"sim-toggle\" onchange=\"toggleSimulator()\"><span class=\"slider\"></span></label>\n"
"</div></div>\n"
"\n"
"<div class=\"card\"><h3>🔢 模拟数量</h3>\n"
"<div class=\"range-wrap\">\n"
"<input type=\"range\" id=\"sim-count\" min=\"1\" max=\"20\" value=\"1\" oninput=\"document.getElementById('count-val').textContent=this.value\">\n"
"<span class=\"range-val\" id=\"count-val\">1</span>\n"
"</div>\n"
"<div class=\"form-row mt-sm\"><div class=\"form-group\"><label>中心纬度(WGS84)</label><input type=\"number\" id=\"sim-center-lat\" step=\"0.000001\" placeholder=\"31.59095700\"></div><div class=\"form-group\"><label>中心经度(WGS84)</label><input type=\"number\" id=\"sim-center-lon\" step=\"0.000001\" placeholder=\"104.748378396\"></div></div>\n"
"<div class=\"mt-sm\"><button class=\"btn btn-primary btn-block\" onclick=\"saveSimConfig()\">💾 应用设置</button></div>\n"
"</div>\n"
"</div>\n"
"\n"
"<div id=\"about\" class=\"page\">\n"
"<div class=\"card\" style=\"text-align:center\"><div style=\"font-size:3em;margin-bottom:12px\">🛸</div><h3>ESP32-C3 RID 管理系统</h3><p style=\"color:var(--text2);font-size:.9em;margin-top:8px\">基于 OpenDroneID 标准<br>支持 GB 42590-2023 / ASTM F3411-22a<br>WiFi AP: rid / 12345678</p></div>\n"
"<div class=\"card\"><h3>📊 系统信息</h3><div class=\"detail-grid\"><div class=\"kv\"><div class=\"k\">芯片</div><div class=\"v\">ESP32-C3</div></div><div class=\"kv\"><div class=\"k\">WiFi SSID</div><div class=\"v\">rid</div></div><div class=\"kv\"><div class=\"k\">在线无人机</div><div class=\"v\" id=\"about-online\">-</div></div><div class=\"kv\"><div class=\"k\">可用内存</div><div class=\"v\" id=\"about-heap\">-</div></div></div></div></div>\n"
"<div class=\"footer\">ESP32-C3 RID Scanner</div>\n"
"\n"
"<script>\n"
"var currentTab=\"dashboard\",allUavs=[],refreshTimer=null;\n"
"\n"
"function switchTab(tab){currentTab=tab;document.querySelectorAll(\".page\").forEach(p=>p.classList.remove(\"active\"));document.querySelectorAll(\"nav a\").forEach(a=>a.classList.remove(\"active\"));var page=document.getElementById(tab);if(page)page.classList.add(\"active\");var link=document.querySelector('nav a[href=\"#'+tab+'\"]');if(link)link.classList.add(\"active\");if(tab===\"drones\")loadDroneList();if(tab===\"dashboard\")loadDashboard();if(tab===\"about\")loadAbout();if(tab===\"simulator\")loadSimConfig()}\n"
"\n"
"async function apiCall(path){try{var resp=await fetch(\"/api/\"+path);return await resp.json()}catch(e){return null}}\n"
"\n"
"async function loadDashboard(){var status=await apiCall(\"status\");if(status){document.getElementById(\"stat-online\").textContent=status.online||0;document.getElementById(\"stat-heap\").textContent=status.heap_kb||0;document.getElementById(\"stat-sim\").textContent=status.sim_running?\"ON\":\"OFF\"}var drones=await apiCall(\"drones\");if(drones&&drones.list){allUavs=drones.list;var html=\"\";drones.list.slice(0,5).forEach(function(u){html+=droneItemHtml(u)});document.getElementById(\"recent-drones\").innerHTML=html||'<div class=\"empty-state\"><div class=\"icon\">📭</div><p>暂无无人机数据</p></div>'}}\n"
"\n"
"function droneItemHtml(u){var n=u.id||(\"MAC: \"+(u.mac||\"?\"));var dot=u.online?'<span class=\"status-dot online\"></span>':'<span class=\"status-dot offline\"></span>';var rssi=u.rssi?\" RSSI:\"+u.rssi+\"dBm\":\"\";var alt=u.altitude_agl?\" Alt:\"+parseFloat(u.altitude_agl).toFixed(1)+\"m\":\"\";var age=ageText(u.age_s);return '<div class=\"drone-item\" onclick=\"showDroneDetail(\\''+(u.mac||\"\")+'\\')\"><div class=\"icon\">🚁</div><div class=\"info\"><div class=\"name\">'+dot+esc(n)+'</div><div class=\"meta\">'+esc(u.model||\"\")+rssi+alt+(age?' <span class=\"age\">'+age+'</span>':\"\")+'</div></div><div class=\"arrow\">›</div></div>'}\n"
"function esc(s){if(!s)return\"\";return String(s).replace(/&/g,\"&amp;\").replace(/</g,\"&lt;\").replace(/>/g,\"&gt;\")}\n"
"function ageText(s){if(s==null||isNaN(s))return\"\";s=Math.max(0,Math.floor(s));if(s<60)return s+\"s前\";if(s<3600)return Math.floor(s/60)+\"m前\";return Math.floor(s/3600)+\"h前\"}\n"
"\n"
"async function loadDroneList(){var drones=await apiCall(\"drones\");if(drones&&drones.list)allUavs=drones.list;var html=\"\";if(allUavs.length===0){document.getElementById(\"drones-empty\").style.display=\"block\"}else{document.getElementById(\"drones-empty\").style.display=\"none\";allUavs.forEach(function(u){html+=droneItemHtml(u)})}document.getElementById(\"all-drones\").innerHTML=html;document.getElementById(\"drone-count\").textContent=\"共 \"+allUavs.length+\" 架\"}\n"
"\n"
"function showDroneDetail(mac){switchTab(\"drone-detail\");var u=null;for(var i=0;i<allUavs.length;i++){if(allUavs[i].mac===mac){u=allUavs[i];break}}if(!u){document.getElementById(\"detail-content\").innerHTML=\"<p>未找到无人机信息</p>\";return}var b=u.online?'<span class=\"badge badge-online\">在线</span>':'<span class=\"badge badge-offline\">离线</span>';var h='<div class=\"flex-between mb-sm\"><h3>🚁 无人机详情</h3>'+b+'</div><div class=\"detail-grid\">';h+=kv(\"ID\",u.id);h+=kv(\"型号\",u.model);h+=kv(\"MAC\",u.mac);h+=kv(\"协议\",u.protocol_name);h+=kv(\"RSSI\",u.rssi?u.rssi+\" dBm\":null);h+=kv(\"最近更新\",ageText(u.age_s));h+=kv(\"纬度\",u.latitude);h+=kv(\"经度\",u.longitude);h+=kv(\"海拔高度\",u.altitude_msl?u.altitude_msl+\" m\":null);h+=kv(\"相对高度\",u.altitude_agl?u.altitude_agl+\" m\":null);h+=kv(\"水平速度\",u.speed_h?u.speed_h+\" m/s\":null);h+=kv(\"垂直速度\",u.speed_v?u.speed_v+\" m/s\":null);h+=kv(\"航向\",u.heading?u.heading+\"°\":null);h+=kv(\"状态\",u.status_text);h+=kv(\"飞手ID\",u.operator_id);h+=kv(\"飞手纬度\",u.operator_lat);h+=kv(\"飞手经度\",u.operator_lon);h+='</div>';document.getElementById(\"detail-content\").innerHTML=h;var lat=parseFloat(u.latitude)||0;var lon=parseFloat(u.longitude)||0;if(lat!==0&&lon!==0){document.getElementById(\"nav-drone\").href=\"https://uri.amap.com/marker?position=\"+lon+\",\"+lat+\"&name=\"+encodeURIComponent(u.id||\"无人机\");document.getElementById(\"nav-drone\").style.display=\"flex\";document.getElementById(\"map-hint\").textContent=\"位置: \"+lat.toFixed(6)+\", \"+lon.toFixed(6)}else{document.getElementById(\"nav-drone\").style.display=\"none\";document.getElementById(\"map-hint\").textContent=\"无有效位置信息\"}var olat=parseFloat(u.operator_lat)||0;var olon=parseFloat(u.operator_lon)||0;if(olat!==0&&olon!==0){document.getElementById(\"nav-operator\").href=\"https://uri.amap.com/marker?position=\"+olon+\",\"+olat+\"&name=\"+encodeURIComponent(u.operator_id||\"飞手\");document.getElementById(\"nav-operator\").style.display=\"flex\"}else{document.getElementById(\"nav-operator\").style.display=\"none\"}}\n"
"function kv(k,v){return '<div class=\"kv\"><div class=\"k\">'+esc(k)+'</div><div class=\"v\">'+(v||\"N/A\")+'</div></div>'}\n"
"\n"
"// Simulator\n"
"async function toggleSimulator(){var on=document.getElementById(\"sim-toggle\").checked;await fetch(\"/api/sim_toggle\",{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify({running:on})})}\n"
"async function saveSimConfig(){var cfg={count:parseInt(document.getElementById(\"sim-count\").value),center_lat:parseFloat(document.getElementById(\"sim-center-lat\").value)||0,center_lon:parseFloat(document.getElementById(\"sim-center-lon\").value)||0};await fetch(\"/api/sim_config\",{method:\"POST\",headers:{\"Content-Type\":\"application/json\"},body:JSON.stringify(cfg)});alert(\"✅ 已应用: \"+cfg.count+\" 架无人机\")}\n"
"async function loadSimConfig(){var resp=await fetch(\"/api/sim_config\");var cfg=await resp.json();if(cfg){var e=document.getElementById(\"sim-count\");if(e!==document.activeElement){e.value=cfg.count||1;document.getElementById(\"count-val\").textContent=cfg.count||1}var lat=document.getElementById(\"sim-center-lat\");if(lat!==document.activeElement)lat.value=cfg.center_lat||\"\";var lon=document.getElementById(\"sim-center-lon\");if(lon!==document.activeElement)lon.value=cfg.center_lon||\"\";var tog=document.getElementById(\"sim-toggle\");if(tog!==document.activeElement)tog.checked=cfg.running||false}}\n"
"\n"
"async function loadAbout(){var s=await apiCall(\"status\");if(s){document.getElementById(\"about-online\").textContent=s.online||0;document.getElementById(\"about-heap\").textContent=(s.heap_kb||0)+\" KB\"}}\n"
"\n"
"function startRefresh(){if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(function(){if(currentTab===\"dashboard\")loadDashboard();if(currentTab===\"simulator\")loadSimConfig()},5000)}\n"
"\n"
"// 页面自包含：无需外部 CDN 依赖，加载后直接初始化\n"
"loadDashboard();loadSimConfig();startRefresh();\n"
"\n"
"</script>\n"
"</body>\n"
"</html>\n"
;